"""add notify_mention and notify_assigned to notification_configs

Revision ID: 07ab187d3790
Revises: f1a2b3c4d5e6
Create Date: 2026-07-12 21:41:30.094642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ab187d3790'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Both default to enabled. server_default="1" backfills existing config rows
    # (Python-side default=True only applies to new ORM inserts), so users who
    # already have a NotificationConfig keep getting mention/assignment mail.
    op.add_column('notification_configs',
                  sa.Column('notify_mention', sa.Boolean(), nullable=False, server_default="1"))
    op.add_column('notification_configs',
                  sa.Column('notify_assigned', sa.Boolean(), nullable=False, server_default="1"))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_configs', 'notify_assigned')
    op.drop_column('notification_configs', 'notify_mention')
    # ### end Alembic commands ###
