"""add external identity to tests for import dedup

Revision ID: 493dffa9cfee
Revises: c3d1f7a90b21
Create Date: 2026-07-06 17:27:48.447138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493dffa9cfee'
down_revision = 'c3d1f7a90b21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('external_provider', sa.String(length=64), nullable=True))
    op.add_column('tests', sa.Column('external_key', sa.String(length=128), nullable=True))
    op.add_column('tests', sa.Column('external_url', sa.String(length=512), nullable=True))
    op.create_index('ix_test_external', 'tests', ['external_provider', 'external_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_external', table_name='tests')
    op.drop_column('tests', 'external_url')
    op.drop_column('tests', 'external_key')
    op.drop_column('tests', 'external_provider')
    # ### end Alembic commands ###
