"""baseline schema

Revision ID: e8e566ab263b
Revises: 
Create Date: 2026-07-02 21:54:00.741089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e566ab263b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('who', sa.String(length=255), nullable=True),
    sa.Column('what', sa.String(length=255), nullable=True),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('when', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('token_prefix', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=True),
    sa.Column('last_used_at', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integrations',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('configured_by', sa.String(length=255), nullable=True),
    sa.Column('last_sync', sa.String(length=64), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_token', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_token')
    )
    op.create_table('pipelines',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('duration', sa.String(length=64), nullable=True),
    sa.Column('commit', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('when', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Integer(), nullable=True),
    sa.Column('failed', sa.Integer(), nullable=True),
    sa.Column('blocked', sa.Integer(), nullable=True),
    sa.Column('started', sa.String(length=64), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('env', sa.String(length=255), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('source_run_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('totp_secret', sa.String(length=255), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('webhooks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('last_status_code', sa.Integer(), nullable=True),
    sa.Column('last_delivery_at', sa.String(length=64), nullable=True),
    sa.Column('hmac_secret', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folders',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.String(length=255), nullable=True),
    sa.Column('project_id', sa.String(length=255), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('slack_enabled', sa.Boolean(), nullable=True),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_user', sa.String(length=255), nullable=True),
    sa.Column('smtp_pass', sa.String(length=255), nullable=True),
    sa.Column('smtp_from', sa.String(length=255), nullable=True),
    sa.Column('slack_webhook_url', sa.String(length=512), nullable=True),
    sa.Column('notify_run_complete', sa.Boolean(), nullable=True),
    sa.Column('notify_consecutive_fail', sa.Boolean(), nullable=True),
    sa.Column('consecutive_fail_threshold', sa.Integer(), nullable=True),
    sa.Column('notify_comment', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_identities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('oauth_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'oauth_id', name='uq_provider_oauth_id')
    )
    op.create_table('oauth_pending_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_token', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('oauth_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_token')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.String(length=64), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('totp_recovery_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tests',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('folder_id', sa.String(length=255), nullable=True),
    sa.Column('project_id', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('priority', sa.String(length=32), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('auto', sa.Boolean(), nullable=True),
    sa.Column('runner', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=64), nullable=True),
    sa.Column('last_run_at', sa.String(length=64), nullable=True),
    sa.Column('duration', sa.String(length=64), nullable=True),
    sa.Column('repo_url', sa.String(length=512), nullable=True),
    sa.Column('source_path', sa.String(length=512), nullable=True),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('source_body', sa.Text(), nullable=True),
    sa.Column('source_synced_at', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.String(length=255), nullable=True),
    sa.Column('who', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('when', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defects',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('test_id', sa.String(length=255), nullable=True),
    sa.Column('run_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=True),
    sa.Column('test_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('actual_result', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_categories',
    sa.Column('test_id', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE')
    )
    op.create_table('test_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('step_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_case_id', sa.Integer(), nullable=False),
    sa.Column('test_step_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('actual_result', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_case_id'], ['run_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_step_id'], ['test_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step_results')
    op.drop_table('test_steps')
    op.drop_table('test_categories')
    op.drop_table('run_cases')
    op.drop_table('defects')
    op.drop_table('comments')
    op.drop_table('user_favorites')
    op.drop_table('tests')
    op.drop_table('totp_recovery_codes')
    op.drop_table('password_reset_tokens')
    op.drop_table('oauth_pending_links')
    op.drop_table('oauth_identities')
    op.drop_table('notifications')
    op.drop_table('notification_configs')
    op.drop_table('folders')
    op.drop_table('audit_log')
    op.drop_table('attachments')
    op.drop_table('webhooks')
    op.drop_table('users')
    op.drop_table('runs')
    op.drop_table('projects')
    op.drop_table('pipelines')
    op.drop_table('oauth_states')
    op.drop_table('integrations')
    op.drop_table('categories')
    op.drop_table('api_tokens')
    op.drop_table('activity')
    # ### end Alembic commands ###
